services:
  postgres:
    container_name: postgres
    image: postgres:11.5-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=student-management-system
  # redis:
  #   container_name: redis
  #   image: 'bitnami/redis:latest'
  #   restart: always
  #   ports:
  #     - 6379:6379
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes

  # pgadmin4:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   restart: always
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@mail.com
  #     - PGADMIN_DEFAULT_PASSWORD=password
